include(cmake/board.cmake)

set(LINUX_SRC_DIR ${PROJECT_SOURCE_DIR}/linux)
set(LINUX_BUILD_DIR ${BOARD_BUILD_DIR})
set(CMAKE_INSTALL_PREFIX ${LINUX_BUILD_DIR}/fakeroot)
set(LINUX_CROSSCOMPILE_PARAMS ARCH=${ARCH} CROSS_COMPILE=${CROSS_COMPILE} O=${LINUX_BUILD_DIR})
set(LINUX_MAKE_PARAMS) # Currently there is nothing here
set(LINUX_BUILD_TARGETS all)
set(LINUX_INSTALL_TARGETS modules_install)
set(LINUX_INSTALL_FLAFS INSTALL_MOD_PATH=${CMAKE_INSTALL_PREFIX})

add_custom_target( os-configure
    COMMAND sh ${PROJECT_SOURCE_DIR}/setup.env
    COMMAND make ${LINUX_MAKE_PARAMS} distclean
    COMMAND make ${LINUX_MAKE_PARAMS} ${LINUX_CROSSCOMPILE_PARAMS} ${DEFCONFIG}
    WORKING_DIRECTORY ${LINUX_SRC_DIR}
)

add_custom_target( os-build
    COMMAND sh ${PROJECT_SOURCE_DIR}/setup.env
    COMMAND make ${LINUX_MAKE_PARAMS} clean
    COMMAND make ${LINUX_MAKE_PARAMS} ${LINUX_CROSSCOMPILE_PARAMS} ${LINUX_BUILD_TARGETS}
    COMMAND make ${LINUX_MAKE_PARAMS} ${LINUX_CROSSCOMPILE_PARAMS} ${LINUX_INSTALL_FLAFS} ${LINUX_INSTALL_TARGETS}
    WORKING_DIRECTORY ${LINUX_SRC_DIR}
)

add_custom_target( os-clean
    COMMAND make ${LINUX_MAKE_PARAMS} distclean
    WORKING_DIRECTORY ${LINUX_SRC_DIR}
)
