if (NOT BUILD_TOOL_NAME)
    message("== The BUILD_TOOL_NAME value has NOT been set, use default")
    set(BUILD_TOOL_NAME arm-linux-gnueabihf)
endif ()

if (DEFINED $ENV{TOOLCHAIN_PATH})
    message( FATAL_ERROR "== Please set TOOLCHAIN_PATH env variable. Aborting...")
endif ()

set(CMAKE_SYSTEM_NAME Linux)

set(CMAKE_CXX_COMPILER  $ENV{TOOLCHAIN_PATH}/${BUILD_TOOL_NAME}-g++)
set(CMAKE_C_COMPILER    $ENV{TOOLCHAIN_PATH}/${BUILD_TOOL_NAME}-gcc)
set(CMAKE_ASM_COMPILER  $ENV{TOOLCHAIN_PATH}/${BUILD_TOOL_NAME}-gcc)
set(SIZE_COMMAND        $ENV{TOOLCHAIN_PATH}/${BUILD_TOOL_NAME}-size)
set(OBJCOPY_COMMAND     $ENV{TOOLCHAIN_PATH}/${BUILD_TOOL_NAME}-objcopy)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
