if (DEFINED $ENV{LINUX_TOOLCHAIN_PATH})
    message( FATAL_ERROR "== Please set LINUX_TOOLCHAIN_PATH env variable. Aborting...")
endif ()

if (DEFINED $ENV{QB_BUILD_TOOL_NAME})
    message( FATAL_ERROR "== Please set QB_BUILD_TOOL_NAME env variable. Aborting...")
endif ()

if (DEFINED $ENV{QB_TOOLCHAIN_PATH})
    message( FATAL_ERROR "== Please set QB_TOOLCHAIN_PATH env variable. Aborting...")
endif ()

set(CMAKE_SYSTEM_NAME Linux)

set(CMAKE_CXX_COMPILER  $ENV{QB_TOOLCHAIN_PATH}/$ENV{QB_BUILD_TOOL_NAME}-g++)
set(CMAKE_C_COMPILER    $ENV{QB_TOOLCHAIN_PATH}/$ENV{QB_BUILD_TOOL_NAME}-gcc)
set(CMAKE_ASM_COMPILER  $ENV{QB_TOOLCHAIN_PATH}/$ENV{QB_BUILD_TOOL_NAME}-gcc)
set(SIZE_COMMAND        $ENV{QB_TOOLCHAIN_PATH}/$ENV{QB_BUILD_TOOL_NAME}-size)
set(OBJCOPY_COMMAND     $ENV{QB_TOOLCHAIN_PATH}/$ENV{QB_BUILD_TOOL_NAME}-objcopy)

set(CROSS_C_LINKER      $ENV{QB_TOOLCHAIN_PATH}/$ENV{QB_BUILD_TOOL_NAME}-ld)
set(CROSS_ASM_COMPILER  $ENV{QB_TOOLCHAIN_PATH}/$ENV{QB_BUILD_TOOL_NAME}-as)
