
set(CMAKE_SYSTEM_NAME Linux)
set(TOOL_NAME arm-linux-gnueabihf)

set(CMAKE_CXX_COMPILER  ${TOOLCHAIN_DIR}/bin/${TOOL_NAME}-g++)
set(CMAKE_C_COMPILER    ${TOOLCHAIN_DIR}/bin/${TOOL_NAME}-gcc)
set(CMAKE_ASM_COMPILER  ${TOOLCHAIN_DIR}/bin/${TOOL_NAME}-gcc)
set(SIZE_COMMAND        ${TOOLCHAIN_DIR}/bin/${TOOL_NAME}-size)
set(OBJCOPY_COMMAND     ${TOOLCHAIN_DIR}/bin/${TOOL_NAME}-objcopy)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
